//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace fleet_tracker.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class GroupDevice
    {
        public int @int { get; set; }
        public Nullable<int> device_id { get; set; }
        public Nullable<int> group_id { get; set; }
    
        public virtual Device Device { get; set; }
        public virtual Group Group { get; set; }
    }
}
