//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace fleet_tracker.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Invoice
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Invoice()
        {
            this.Ticks = new HashSet<Tick>();
        }
    
        public int ID { get; set; }
        public string Token { get; set; }
        public Nullable<int> RouteID { get; set; }
        public Nullable<int> VehicleID { get; set; }
        public Nullable<int> DeviceID { get; set; }
        public Nullable<int> DriverID { get; set; }
        public Nullable<int> GroupID { get; set; }
        public Nullable<short> Finished { get; set; }
        public Nullable<System.DateTime> CreatedAt { get; set; }
        public Nullable<System.DateTime> UpdatedAt { get; set; }
        public Nullable<System.DateTime> StartedAt { get; set; }
        public Nullable<System.DateTime> FinishedAt { get; set; }
    
        public virtual Device Device { get; set; }
        public virtual Driver Driver { get; set; }
        public virtual Group Group { get; set; }
        public virtual Route Route { get; set; }
        public virtual Vehicle Vehicle { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tick> Ticks { get; set; }
    }
}
