//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace fleet_tracker.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tick
    {
        public int ID { get; set; }
        public Nullable<int> DeviceID { get; set; }
        public Nullable<int> InvoiceID { get; set; }
        public Nullable<decimal> Lat { get; set; }
        public Nullable<decimal> Long { get; set; }
        public string Message { get; set; }
        public Nullable<System.DateTime> CreatedAt { get; set; }
    
        public virtual Device Device { get; set; }
        public virtual Invoice Invoice { get; set; }
    }
}
